# Author: Diego Gómez
# Email: dngomez.e@gmail.com
# Date: 2025-04-06
# Version: 1.0
# Description: Compose file to create the entire aurorus project stack

services:
  database:
    image: postgres:17.4
    container_name: database
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  pgdata:
    driver: local
